
package com.test.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://92.168.0.1/")
public interface ServiceSoap {


    /**
     * ������ʾ
     * 
     * @param passWord
     * @param secretkey
     * @param loginName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MembershipVerification", action = "http://92.168.0.1/MembershipVerification")
    @WebResult(name = "MembershipVerificationResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "MembershipVerification", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MembershipVerification")
    @ResponseWrapper(localName = "MembershipVerificationResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MembershipVerificationResponse")
    public String membershipVerification(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "loginName", targetNamespace = "http://92.168.0.1/")
        String loginName,
        @WebParam(name = "passWord", targetNamespace = "http://92.168.0.1/")
        String passWord);

    /**
     * ������Կ
     * 
     * @param secretkey
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SecretKeycheck", action = "http://92.168.0.1/SecretKeycheck")
    @WebResult(name = "SecretKeycheckResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "SecretKeycheck", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SecretKeycheck")
    @ResponseWrapper(localName = "SecretKeycheckResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SecretKeycheckResponse")
    public boolean secretKeycheck(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey);

    /**
     * ��Ա��¼
     * 
     * @param passWord
     * @param secretkey
     * @param loginName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Security_check", action = "http://92.168.0.1/Security_check")
    @WebResult(name = "Security_checkResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "Security_check", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SecurityCheck")
    @ResponseWrapper(localName = "Security_checkResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SecurityCheckResponse")
    public int securityCheck(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "loginName", targetNamespace = "http://92.168.0.1/")
        String loginName,
        @WebParam(name = "passWord", targetNamespace = "http://92.168.0.1/")
        String passWord);

    /**
     * ��Ա�ֻ�����ע��
     * 
     * @param mobilePhoneNO
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MemberQuickRegister", action = "http://92.168.0.1/MemberQuickRegister")
    @WebResult(name = "MemberQuickRegisterResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "MemberQuickRegister", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberQuickRegister")
    @ResponseWrapper(localName = "MemberQuickRegisterResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberQuickRegisterResponse")
    public String memberQuickRegister(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "mobilePhoneNO", targetNamespace = "http://92.168.0.1/")
        String mobilePhoneNO);

    /**
     * ��Ա��ϸע��
     * 
     * @param loginPass
     * @param sex
     * @param phone
     * @param occupation
     * @param post
     * @param contact
     * @param secretkey
     * @param cardNO
     * @param mobilePhone
     * @param duty
     * @param email
     * @param address
     * @param age
     * @param memberName
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "MemberDetailRegister", action = "http://92.168.0.1/MemberDetailRegister")
    @WebResult(name = "MemberDetailRegisterResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "MemberDetailRegister", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberDetailRegister")
    @ResponseWrapper(localName = "MemberDetailRegisterResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberDetailRegisterResponse")
    public boolean memberDetailRegister(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "memberName", targetNamespace = "http://92.168.0.1/")
        String memberName,
        @WebParam(name = "loginPass", targetNamespace = "http://92.168.0.1/")
        String loginPass,
        @WebParam(name = "contact", targetNamespace = "http://92.168.0.1/")
        String contact,
        @WebParam(name = "sex", targetNamespace = "http://92.168.0.1/")
        String sex,
        @WebParam(name = "age", targetNamespace = "http://92.168.0.1/")
        int age,
        @WebParam(name = "mobilePhone", targetNamespace = "http://92.168.0.1/")
        String mobilePhone,
        @WebParam(name = "phone", targetNamespace = "http://92.168.0.1/")
        String phone,
        @WebParam(name = "occupation", targetNamespace = "http://92.168.0.1/")
        String occupation,
        @WebParam(name = "duty", targetNamespace = "http://92.168.0.1/")
        int duty,
        @WebParam(name = "email", targetNamespace = "http://92.168.0.1/")
        String email,
        @WebParam(name = "cardNO", targetNamespace = "http://92.168.0.1/")
        String cardNO,
        @WebParam(name = "address", targetNamespace = "http://92.168.0.1/")
        String address,
        @WebParam(name = "post", targetNamespace = "http://92.168.0.1/")
        String post);

    /**
     * ��������ս�Ͷ��Ϣ
     * 
     * @param tradeType
     * @param tradeBoxID
     * @param memberPhoneNO
     * @param resourceCatalog
     * @param secretkey
     * @param memberNo
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "InsertOrUpdateTrade", action = "http://92.168.0.1/InsertOrUpdateTrade")
    @WebResult(name = "InsertOrUpdateTradeResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "InsertOrUpdateTrade", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.InsertOrUpdateTrade")
    @ResponseWrapper(localName = "InsertOrUpdateTradeResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.InsertOrUpdateTradeResponse")
    public boolean insertOrUpdateTrade(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "TradeType", targetNamespace = "http://92.168.0.1/")
        String tradeType,
        @WebParam(name = "ResourceCatalog", targetNamespace = "http://92.168.0.1/")
        int resourceCatalog,
        @WebParam(name = "MemberPhoneNO", targetNamespace = "http://92.168.0.1/")
        String memberPhoneNO,
        @WebParam(name = "MemberNo", targetNamespace = "http://92.168.0.1/")
        String memberNo,
        @WebParam(name = "TradeBoxID", targetNamespace = "http://92.168.0.1/")
        int tradeBoxID);

    /**
     * ���ͻ�б�
     * 
     * @param startdate
     * @param keyvalue
     * @param enddate
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHDYGList", action = "http://92.168.0.1/GetHDYGList")
    @WebResult(name = "GetHDYGListResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "GetHDYGList", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetHDYGList")
    @ResponseWrapper(localName = "GetHDYGListResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetHDYGListResponse")
    public String getHDYGList(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "startdate", targetNamespace = "http://92.168.0.1/")
        String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://92.168.0.1/")
        String enddate,
        @WebParam(name = "keyvalue", targetNamespace = "http://92.168.0.1/")
        String keyvalue);

    /**
     * ���������б�
     * 
     * @param address
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWDCXList", action = "http://92.168.0.1/GetWDCXList")
    @WebResult(name = "GetWDCXListResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "GetWDCXList", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetWDCXList")
    @ResponseWrapper(localName = "GetWDCXListResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetWDCXListResponse")
    public String getWDCXList(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "Address", targetNamespace = "http://92.168.0.1/")
        String address);

    /**
     * ��ҳ���������б�
     * 
     * @param pagesize
     * @param address
     * @param pagenum
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWDCXListPage", action = "http://92.168.0.1/GetWDCXListPage")
    @WebResult(name = "GetWDCXListPageResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "GetWDCXListPage", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetWDCXListPage")
    @ResponseWrapper(localName = "GetWDCXListPageResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetWDCXListPageResponse")
    public String getWDCXListPage(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "Address", targetNamespace = "http://92.168.0.1/")
        String address,
        @WebParam(name = "pagesize", targetNamespace = "http://92.168.0.1/")
        String pagesize,
        @WebParam(name = "pagenum", targetNamespace = "http://92.168.0.1/")
        String pagenum);

    /**
     * ��ҳ���ͻ�б�
     * 
     * @param pagesize
     * @param startdate
     * @param pagenum
     * @param keyvalue
     * @param enddate
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetHDYGListPage", action = "http://92.168.0.1/GetHDYGListPage")
    @WebResult(name = "GetHDYGListPageResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "GetHDYGListPage", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetHDYGListPage")
    @ResponseWrapper(localName = "GetHDYGListPageResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetHDYGListPageResponse")
    public String getHDYGListPage(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "startdate", targetNamespace = "http://92.168.0.1/")
        String startdate,
        @WebParam(name = "enddate", targetNamespace = "http://92.168.0.1/")
        String enddate,
        @WebParam(name = "keyvalue", targetNamespace = "http://92.168.0.1/")
        String keyvalue,
        @WebParam(name = "pagesize", targetNamespace = "http://92.168.0.1/")
        int pagesize,
        @WebParam(name = "pagenum", targetNamespace = "http://92.168.0.1/")
        int pagenum);

    /**
     * ��ȡ��������ǰʮ��
     * 
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://92.168.0.1/getIndividualRank")
    @WebResult(name = "getIndividualRankResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "getIndividualRank", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetIndividualRank")
    @ResponseWrapper(localName = "getIndividualRankResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.GetIndividualRankResponse")
    public String getIndividualRank(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey);

    /**
     * ��ѯ�ǿսֵ�
     * 
     * @param secretkey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://92.168.0.1/selectTown")
    @WebResult(name = "selectTownResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "selectTown", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SelectTown")
    @ResponseWrapper(localName = "selectTownResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.SelectTownResponse")
    public String selectTown(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey);

    /**
     * ��Ա��¼���ػ�Ա��Ϣ
     * 
     * @param passWord
     * @param secretkey
     * @param loginName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LoginMemberMessage", action = "http://92.168.0.1/LoginMemberMessage")
    @WebResult(name = "LoginMemberMessageResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "LoginMemberMessage", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.LoginMemberMessage")
    @ResponseWrapper(localName = "LoginMemberMessageResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.LoginMemberMessageResponse")
    public String loginMemberMessage(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "loginName", targetNamespace = "http://92.168.0.1/")
        String loginName,
        @WebParam(name = "passWord", targetNamespace = "http://92.168.0.1/")
        String passWord);

    /**
     * �����������䡢��Ա�Ų�ѯ��ʷ��Ͷ��¼
     * 
     * @param submitDateEnd
     * @param submitDateStart
     * @param mobilePhone
     * @param secretkey
     * @param memberNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ElectronOrderWebService", action = "http://92.168.0.1/ElectronOrderWebService")
    @WebResult(name = "ElectronOrderWebServiceResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "ElectronOrderWebService", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.ElectronOrderWebService")
    @ResponseWrapper(localName = "ElectronOrderWebServiceResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.ElectronOrderWebServiceResponse")
    public String electronOrderWebService(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "SubmitDateStart", targetNamespace = "http://92.168.0.1/")
        String submitDateStart,
        @WebParam(name = "SubmitDateEnd", targetNamespace = "http://92.168.0.1/")
        String submitDateEnd,
        @WebParam(name = "MemberNo", targetNamespace = "http://92.168.0.1/")
        String memberNo,
        @WebParam(name = "MobilePhone", targetNamespace = "http://92.168.0.1/")
        String mobilePhone);

    /**
     * �����������䡢��Ա�Ų�ѯ���ֱ䶯��ϸ
     * 
     * @param createDateEnd
     * @param createDateStart
     * @param mobilePhone
     * @param secretkey
     * @param memberNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MemberPointDetailWebService", action = "http://92.168.0.1/MemberPointDetailWebService")
    @WebResult(name = "MemberPointDetailWebServiceResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "MemberPointDetailWebService", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberPointDetailWebService")
    @ResponseWrapper(localName = "MemberPointDetailWebServiceResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.MemberPointDetailWebServiceResponse")
    public String memberPointDetailWebService(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "CreateDateStart", targetNamespace = "http://92.168.0.1/")
        String createDateStart,
        @WebParam(name = "CreateDateEnd", targetNamespace = "http://92.168.0.1/")
        String createDateEnd,
        @WebParam(name = "MemberNo", targetNamespace = "http://92.168.0.1/")
        String memberNo,
        @WebParam(name = "MobilePhone", targetNamespace = "http://92.168.0.1/")
        String mobilePhone);

    /**
     * ������ּ�����ϸ��
     * 
     * @param reducePointType
     * @param tradeBoxID
     * @param commodityType
     * @param reduceTime
     * @param reducePointReason
     * @param secretkey
     * @param contactMobileNO
     * @param point
     * @param contactName
     * @param serialNO
     * @param commodityID
     * @param commodityNumber
     * @param loginName
     * @param contactAddress
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "InsertExchangeDetail", action = "http://92.168.0.1/InsertExchangeDetail")
    @WebResult(name = "InsertExchangeDetailResult", targetNamespace = "http://92.168.0.1/")
    @RequestWrapper(localName = "InsertExchangeDetail", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.InsertExchangeDetail")
    @ResponseWrapper(localName = "InsertExchangeDetailResponse", targetNamespace = "http://92.168.0.1/", className = "com.test.cxf.InsertExchangeDetailResponse")
    public boolean insertExchangeDetail(
        @WebParam(name = "secretkey", targetNamespace = "http://92.168.0.1/")
        String secretkey,
        @WebParam(name = "tradeBoxID", targetNamespace = "http://92.168.0.1/")
        int tradeBoxID,
        @WebParam(name = "reducePointType", targetNamespace = "http://92.168.0.1/")
        String reducePointType,
        @WebParam(name = "reducePointReason", targetNamespace = "http://92.168.0.1/")
        String reducePointReason,
        @WebParam(name = "reduceTime", targetNamespace = "http://92.168.0.1/")
        String reduceTime,
        @WebParam(name = "loginName", targetNamespace = "http://92.168.0.1/")
        String loginName,
        @WebParam(name = "commodityID", targetNamespace = "http://92.168.0.1/")
        int commodityID,
        @WebParam(name = "commodityNumber", targetNamespace = "http://92.168.0.1/")
        String commodityNumber,
        @WebParam(name = "point", targetNamespace = "http://92.168.0.1/")
        int point,
        @WebParam(name = "contactName", targetNamespace = "http://92.168.0.1/")
        String contactName,
        @WebParam(name = "contactMobileNO", targetNamespace = "http://92.168.0.1/")
        String contactMobileNO,
        @WebParam(name = "contactAddress", targetNamespace = "http://92.168.0.1/")
        String contactAddress,
        @WebParam(name = "commodityType", targetNamespace = "http://92.168.0.1/")
        String commodityType,
        @WebParam(name = "serialNO", targetNamespace = "http://92.168.0.1/")
        String serialNO);

}
