
package com.webservice.jdk.wsimport.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CxfDemoImplService", targetNamespace = "http://server.cxf.webservice.com/", wsdlLocation = "http://localhost:8089/webserviceCxfDemo/ws/cxfDemo?wsdl")
public class CxfDemoImplService
    extends Service
{

    private final static URL CXFDEMOIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8089/webserviceCxfDemo/ws/cxfDemo?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CXFDEMOIMPLSERVICE_WSDL_LOCATION = url;
    }

    public CxfDemoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfDemoImplService() {
        super(CXFDEMOIMPLSERVICE_WSDL_LOCATION, new QName("http://server.cxf.webservice.com/", "CxfDemoImplService"));
    }

    /**
     * 
     * @return
     *     returns CxfDemo
     */
    @WebEndpoint(name = "CxfDemoImplPort")
    public CxfDemo getCxfDemoImplPort() {
        return (CxfDemo)super.getPort(new QName("http://server.cxf.webservice.com/", "CxfDemoImplPort"), CxfDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfDemo
     */
    @WebEndpoint(name = "CxfDemoImplPort")
    public CxfDemo getCxfDemoImplPort(WebServiceFeature... features) {
        return (CxfDemo)super.getPort(new QName("http://server.cxf.webservice.com/", "CxfDemoImplPort"), CxfDemo.class, features);
    }

}
